"""fixed date_created

Revision ID: 052333e5d986
Revises: 
Create Date: 2021-04-09 15:00:58.863500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052333e5d986'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

        #op.add_column('task', sa.Column('date_created', sa.DateTime(), nullable=True))
        #op.create_index(op.f('ix_task_date_created'), 'task', ['date_created'], unique=False)
        with op.batch_alter_table('task') as batch_op:
            batch_op.drop_column('data_created')
            #batch_op.drop_column('task', 'data_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('data_created', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_task_date_created'), table_name='task')
    op.drop_column('task', 'date_created')
    # ### end Alembic commands ###
