"""added date completed column

Revision ID: ea2c6ee11a06
Revises: 052333e5d986
Create Date: 2021-04-10 15:00:19.405120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2c6ee11a06'
down_revision = '052333e5d986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('date_completed', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_task_date_completed'), 'task', ['date_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_date_completed'), table_name='task')
    op.drop_column('task', 'date_completed')
    # ### end Alembic commands ###
